apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: identity

resources:
  - namespace.yaml
  - postgresql-secret.yaml
  - postgresql-configmap.yaml
  - postgresql-pvc.yaml
  - postgresql-deployment.yaml
  - postgresql-service.yaml

images:
  - name: postgres
    newTag: "15-alpine"

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app: identity-postgresql
      version: v1.0.0 